name = "Fnige's Minecraft Server (1.19.2)"
author = "Fnige"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43cd96e1083a9d2c1fafa7b4f05ffb58c53c02c5f4e7b1409220e98c237f4332"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.1"

[options]
acceptable-game-versions = ["1.19"]
