name = "Fnige's Minecraft Server (1.19.2)"
author = "Fnige"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdde467e72cf8870571163c6e4a98b651eb3803ac99c26a18c3f8221e2af9d7f"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.1"
