name = "Fnige's Minecraft Server (1.19.2)"
author = "Fnige"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f9a8f6e314b145e48fe8c2b37ff07f2801d47b9191de8e7d6a20560f41b6993"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.1"
