name = "Fnige's Minecraft Server (1.19.2)"
author = "Fnige"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a84cf7d96bd38c45c9f28d0af30f0f7b07b560d11e2c0d5c0f12459b6960fc5"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.1"
